#include "embedded_assets.h"

const char LG_INDEX_HTML[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "  <meta charset=\"UTF-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "  <title>Logic Gate Game</title>\n"
    "  <link rel=\"stylesheet\" href=\"/styles.css\">\n"
    "</head>\n"
    "<body>\n"
    "  <main class=\"game-shell\">\n"
    "    <header class=\"hud\">\n"
    "      <div class=\"badge\">Moves: <span id=\"moves\">0</span></div>\n"
    "      <div id=\"status\" class=\"badge status\">Connecting...</div>\n"
    "      <div class=\"badge level-control\">Level: <select id=\"levelSelect\"></select></div>\n"
    "    </header>\n"
    "    <section class=\"board\">\n"
    "      <svg class=\"wires\" viewBox=\"0 0 1000 620\" preserveAspectRatio=\"none\">\n"
    "        <polyline id=\"wire-sa-and\" points=\"120,180 300,180 300,320 420,320\" />\n"
    "        <polyline id=\"wire-sb-and\" points=\"120,350 315,350 315,360 420,360\" />\n"
    "        <polyline id=\"wire-sa-not\" points=\"120,180 280,180 280,110 400,110\" />\n"
    "        <polyline id=\"wire-and-or\" points=\"560,340 660,340 660,240 700,240\" />\n"
    "        <polyline id=\"wire-not-or\" points=\"500,110 620,110 620,200 700,200\" />\n"
    "        <polyline id=\"wire-or-bulb\" points=\"840,220 900,220\" />\n"
    "      </svg>\n"

    "      <article class=\"node input\" data-id=\"SwitchA\">\n"
    "        <div class=\"lamp\"></div>\n"
    "        <h3>Switch A</h3>\n"
    "        <p class=\"state\">OFF</p>\n"
    "      </article>\n"

    "      <article class=\"node input\" data-id=\"SwitchB\">\n"
    "        <div class=\"lamp\"></div>\n"
    "        <h3>Switch B</h3>\n"
    "        <p class=\"state\">OFF</p>\n"
    "      </article>\n"

    "      <article class=\"node gate small\" data-id=\"NotA\">\n"
    "        <h3>NOT</h3>\n"
    "        <div class=\"lamp\"></div>\n"
    "      </article>\n"

    "      <article class=\"node gate\" data-id=\"And1\">\n"
    "        <h3>AND</h3>\n"
    "        <div class=\"lamp\"></div>\n"
    "      </article>\n"

    "      <article class=\"node gate\" data-id=\"Or1\">\n"
    "        <h3>OR</h3>\n"
    "        <div class=\"lamp\"></div>\n"
    "      </article>\n"

    "      <article class=\"node output\" data-id=\"Bulb1\">\n"
    "        <div class=\"lamp\"></div>\n"
    "        <h3>Bulb</h3>\n"
    "      </article>\n"

    "      <aside id=\"signalStack\" class=\"signal-stack\"></aside>\n"
    "    </section>\n"

    "    <footer class=\"controls\">\n"
    "      <button type=\"button\" class=\"ctrl\" title=\"Home\">HOME</button>\n"
    "      <button type=\"button\" class=\"ctrl\" title=\"Sound\">MUTE</button>\n"
    "    </footer>\n"
    "    <section class=\"meta\">\n"
    "      <div class=\"badge objectives\">Objectives: <span id=\"objectiveText\">-</span></div>\n"
    "      <div id=\"winBanner\" class=\"badge win-banner\" hidden>Level Complete!</div>\n"
    "    </section>\n"
    "  </main>\n"
    "  <script src=\"/app.js\"></script>\n"
    "</body>\n"
    "</html>\n";

const size_t LG_INDEX_HTML_LEN = sizeof(LG_INDEX_HTML) - 1;

const char LG_STYLES_CSS[] =
    ":root {\n"
    "  --bg-0: #f4f7fb;\n"
    "  --bg-1: #e8eef6;\n"
    "  --ink-0: #122235;\n"
    "  --ink-1: #4f6378;\n"
    "  --line: #ccdae8;\n"
    "  --card: #ffffff;\n"
    "  --card-edge: #d6e2ef;\n"
    "  --wire-off: #bfcddd;\n"
    "  --wire-on: #37b65b;\n"
    "  --lamp-off: #d8614f;\n"
    "  --lamp-on: #45c467;\n"
    "}\n"
    "* { box-sizing: border-box; user-select: none; }\n"
    "body {\n"
    "  margin: 0; min-height: 100vh; display: grid; place-items: center;\n"
    "  font-family: \"Segoe UI\", \"Helvetica Neue\", Arial, sans-serif;\n"
    "  background: radial-gradient(circle at 20% 0%, #ffffff 0%, var(--bg-0) 42%, var(--bg-1) 100%);\n"
    "  color: var(--ink-0); overflow: hidden;\n"
    "}\n"
    ".game-shell { width: min(1180px, 98vw); padding: 14px 16px 16px; }\n"
    ".hud { display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px; }\n"
    ".badge {\n"
    "  background: rgba(255,255,255,0.72);\n"
    "  border: 1px solid var(--line); border-radius: 999px;\n"
    "  padding: 8px 14px; font-weight: 600; letter-spacing: 0.01em;\n"
    "  color: var(--ink-0); box-shadow: 0 8px 30px rgba(22,43,66,0.08);\n"
    "}\n"
    ".status { min-width: 260px; text-align: center; }\n"
    ".level-control { min-width: 180px; }\n"
    ".level-control select {\n"
    "  margin-left: 6px; border: 1px solid var(--line); border-radius: 8px;\n"
    "  background: #fff; color: var(--ink-0); padding: 4px 8px;\n"
    "}\n"
    ".board {\n"
    "  position: relative; width: 100%; height: min(72vh, 620px);\n"
    "  border-radius: 20px; border: 1px solid var(--line);\n"
    "  background:\n"
    "    linear-gradient(transparent 31px, rgba(142,164,185,0.13) 32px),\n"
    "    linear-gradient(90deg, transparent 31px, rgba(142,164,185,0.13) 32px),\n"
    "    linear-gradient(180deg, #f8fbff, #edf3f9);\n"
    "  background-size: 32px 32px, 32px 32px, 100% 100%;\n"
    "  box-shadow: 0 18px 45px rgba(17,42,68,0.14);\n"
    "}\n"
    ".wires { position: absolute; inset: 0; width: 100%; height: 100%; }\n"
    ".wires polyline {\n"
    "  fill: none; stroke: var(--wire-off); stroke-width: 5;\n"
    "  stroke-linecap: round; stroke-linejoin: round;\n"
    "  transition: stroke 140ms ease, opacity 140ms ease; opacity: 0.9;\n"
    "}\n"
    ".wires polyline.on { stroke: var(--wire-on); opacity: 1; }\n"
    ".node {\n"
    "  position: absolute; background: var(--card);\n"
    "  border: 1px solid var(--card-edge); border-radius: 12px;\n"
    "  box-shadow: 0 10px 26px rgba(16,39,61,0.09);\n"
    "  display: grid; place-items: center; gap: 6px;\n"
    "  color: var(--ink-0);\n"
    "  transition: transform 130ms ease, box-shadow 130ms ease, border-color 130ms ease;\n"
    "}\n"
    ".node h3 { margin: 0; font-size: clamp(0.95rem, 1.7vw, 1.35rem); font-weight: 600; letter-spacing: 0.02em; }\n"
    ".node .state { margin: 0; font-size: 0.75rem; letter-spacing: 0.08em; font-weight: 700; color: var(--ink-1); }\n"
    ".node.input { width: 120px; height: 150px; left: 3%; }\n"
    ".node.input[data-id=\"SwitchA\"] { top: 12%; }\n"
    ".node.input[data-id=\"SwitchB\"] { top: 44%; }\n"
    ".node.gate { width: 150px; height: 130px; }\n"
    ".node.gate.small { width: 110px; height: 88px; }\n"
    ".node.gate[data-id=\"NotA\"] { left: 40%; top: 8%; }\n"
    ".node.gate[data-id=\"And1\"] { left: 42%; top: 45%; }\n"
    ".node.gate[data-id=\"Or1\"] { left: 64%; top: 25%; }\n"
    ".node.output { width: 112px; height: 120px; right: 6%; top: 31%; }\n"
    ".node.output h3 { font-size: 1.05rem; }\n"
    ".node.toggleable { cursor: pointer; }\n"
    ".node.toggleable:hover { transform: translateY(-2px); border-color: #a9bfd6; }\n"
    ".node.active { border-color: #95cfa4; box-shadow: 0 12px 30px rgba(34,117,61,0.18); }\n"
    ".lamp {\n"
    "  width: 20px; height: 20px; border-radius: 50%;\n"
    "  border: 1px solid #aeb9c6; background: var(--lamp-off);\n"
    "  box-shadow: 0 0 0 4px rgba(216,97,79,0.13);\n"
    "}\n"
    ".lamp.on {\n"
    "  background: var(--lamp-on);\n"
    "  box-shadow: 0 0 0 4px rgba(69,196,103,0.18), 0 0 18px rgba(69,196,103,0.45);\n"
    "}\n"
    ".signal-stack {\n"
    "  position: absolute; top: 9%; right: 1.2%; width: 126px;\n"
    "  display: grid; gap: 9px;\n"
    "}\n"
    ".signal-row {\n"
    "  display: flex; align-items: center; justify-content: space-between;\n"
    "  background: rgba(255,255,255,0.82); border: 1px solid var(--line);\n"
    "  border-radius: 8px; padding: 6px 8px; font-size: 0.72rem; font-weight: 600; color: var(--ink-1);\n"
    "}\n"
    ".signal-dot {\n"
    "  width: 12px; height: 12px; border-radius: 50%; border: 1px solid #aeb9c6;\n"
    "  background: var(--lamp-off);\n"
    "}\n"
    ".signal-dot.on { background: var(--lamp-on); box-shadow: 0 0 10px rgba(69,196,103,0.45); }\n"
    ".controls { display: flex; gap: 10px; margin-top: 12px; }\n"
    ".meta { display: flex; gap: 10px; margin-top: 10px; align-items: center; }\n"
    ".objectives { flex: 1; min-height: 40px; display: flex; align-items: center; }\n"
    ".win-banner { background: #eaf8ee; border-color: #bfe6ca; color: #22653a; font-weight: 700; }\n"
    ".ctrl {\n"
    "  border: 1px solid var(--line); background: #ffffff;\n"
    "  color: var(--ink-1); font-weight: 600; letter-spacing: 0.02em;\n"
    "  border-radius: 10px; min-width: 76px; padding: 10px 12px;\n"
    "  box-shadow: 0 6px 20px rgba(20,42,64,0.08);\n"
    "}\n"
    ".ctrl:hover { border-color: #b4c7db; color: var(--ink-0); }\n"
    "@media (max-width: 900px) {\n"
    "  .board { height: 78vh; }\n"
    "  .signal-stack { position: static; width: 100%; grid-template-columns: repeat(3, minmax(0, 1fr)); padding: 8px; }\n"
    "  .node.output { right: 3%; top: 32%; }\n"
    "}\n";

const size_t LG_STYLES_CSS_LEN = sizeof(LG_STYLES_CSS) - 1;

const char LG_APP_JS[] =
    "const POLL_MS = 150;\n"
    "const statusNode = document.getElementById(\"status\");\n"
    "const movesNode = document.getElementById(\"moves\");\n"
    "const levelSelect = document.getElementById(\"levelSelect\");\n"
    "const objectiveText = document.getElementById(\"objectiveText\");\n"
    "const winBanner = document.getElementById(\"winBanner\");\n"
    "const signalStack = document.getElementById(\"signalStack\");\n"
    "const inFlightToggles = new Set();\n"
    "const signalState = new Map();\n"
    "let lastGoodUpdateMs = 0;\n"
    "let moves = 0;\n"
    "let moveLimit = 0;\n"
    "let failStreak = 0;\n"
    "let currentLevel = \"\";\n"
    "let selectingLevel = false;\n"

    "const wireSources = [\n"
    "  [\"wire-sa-and\", \"SwitchA\"],\n"
    "  [\"wire-sb-and\", \"SwitchB\"],\n"
    "  [\"wire-sa-not\", \"SwitchA\"],\n"
    "  [\"wire-and-or\", \"And1\"],\n"
    "  [\"wire-not-or\", \"NotA\"],\n"
    "  [\"wire-or-bulb\", \"Or1\"]\n"
    "];\n"

    "function escId(id) {\n"
    "  return typeof CSS !== \"undefined\" && CSS.escape ? CSS.escape(id) : id.replace(/[^a-zA-Z0-9_-]/g, \"\");\n"
    "}\n"

    "function setStatus(text, isError = false) {\n"
    "  statusNode.textContent = text;\n"
    "  statusNode.style.color = isError ? \"#c34f3f\" : \"#122235\";\n"
    "}\n"
    "function levelLabel(key) {\n"
    "  if (key === \"easy\") return \"Easy\";\n"
    "  if (key === \"medium\") return \"Medium\";\n"
    "  if (key === \"hard\") return \"Hard\";\n"
    "  return key;\n"
    "}\n"
    "function nodeElement(id) {\n"
    "  return document.querySelector(\".node[data-id=\\\"\" + escId(id) + \"\\\"]\");\n"
    "}\n"
    "function applyNodeState(node) {\n"
    "  const el = nodeElement(node.id);\n"
    "  if (!el) return;\n"
    "  el.classList.toggle(\"active\", !!node.state);\n"
    "  el.classList.toggle(\"toggleable\", !!node.toggleable);\n"
    "  const lamp = el.querySelector(\".lamp\");\n"
    "  const state = el.querySelector(\".state\");\n"
    "  if (lamp) lamp.classList.toggle(\"on\", !!node.state);\n"
    "  if (state) state.textContent = node.state ? \"ON\" : \"OFF\";\n"
    "  el.onclick = node.toggleable ? function() { toggleSwitch(node.id); } : null;\n"
    "  signalState.set(node.id, !!node.state);\n"
    "}\n"
    "function updateWires() {\n"
    "  for (const pair of wireSources) {\n"
    "    const wire = document.getElementById(pair[0]);\n"
    "    if (!wire) continue;\n"
    "    wire.classList.toggle(\"on\", !!signalState.get(pair[1]));\n"
    "  }\n"
    "}\n"
    "function updateSignalStack(nodes) {\n"
    "  signalStack.innerHTML = nodes.map(function(node) {\n"
    "    return \"<div class=\\\"signal-row\\\"><span>\" + node.id + \"</span><span class=\\\"signal-dot \" + (node.state ? \"on\" : \"\") + \"\\\"></span></div>\";\n"
    "  }).join(\"\");\n"
    "}\n"
    "function reconcile(nodes) {\n"
    "  signalState.clear();\n"
    "  for (const node of nodes) applyNodeState(node);\n"
    "  updateWires();\n"
    "  updateSignalStack(nodes);\n"
    "}\n"
    "function renderLevelOptions(data) {\n"
    "  const order = [\"easy\", \"medium\", \"hard\"];\n"
    "  const unlocked = data.unlocked || {};\n"
    "  levelSelect.innerHTML = order.map(function(key) {\n"
    "    const isUnlocked = !!unlocked[key] || key === data.level;\n"
    "    const lock = isUnlocked ? \"\" : \" (Locked)\";\n"
    "    return \"<option value=\\\"\" + key + \"\\\" \" + (isUnlocked ? \"\" : \"disabled\") + \">\" + levelLabel(key) + lock + \"</option>\";\n"
    "  }).join(\"\");\n"
    "  if (data.level) levelSelect.value = data.level;\n"
    "}\n"
    "function renderObjectives(data) {\n"
    "  const objectives = Array.isArray(data.objectives) ? data.objectives : [];\n"
    "  if (objectives.length === 0) {\n"
    "    objectiveText.textContent = \"No objectives\";\n"
    "    return;\n"
    "  }\n"
    "  objectiveText.textContent = objectives.map(function(item) {\n"
    "    return item.id + \"=\" + (item.expected ? \"ON\" : \"OFF\");\n"
    "  }).join(\", \" );\n"
    "}\n"
    "function renderWin(data) {\n"
    "  if (data.won) {\n"
    "    winBanner.hidden = false;\n"
    "    winBanner.textContent = \"Level Complete: \" + (data.levelLabel || levelLabel(data.level));\n"
    "  } else {\n"
    "    winBanner.hidden = true;\n"
    "  }\n"
    "}\n"
    "function applyGameState(data) {\n"
    "  if (!Array.isArray(data.nodes)) return;\n"
    "  if (data.level && data.level !== currentLevel) {\n"
    "    currentLevel = data.level;\n"
    "  }\n"
    "  moves = typeof data.moves === \"number\" ? data.moves : moves;\n"
    "  moveLimit = typeof data.moveLimit === \"number\" ? data.moveLimit : moveLimit;\n"
    "  movesNode.textContent = moveLimit > 0 ? String(moves) + \"/\" + String(moveLimit) : String(moves);\n"
    "  reconcile(data.nodes);\n"
    "  renderLevelOptions(data);\n"
    "  renderObjectives(data);\n"
    "  renderWin(data);\n"
    "}\n"
    "async function selectLevel(level) {\n"
    "  if (!level || selectingLevel) return;\n"
    "  selectingLevel = true;\n"
    "  try {\n"
    "    const res = await fetch(\"/select-level?level=\" + encodeURIComponent(level), { method: \"POST\" });\n"
    "    if (!res.ok) {\n"
    "      const payload = await res.json().catch(function() { return {}; });\n"
    "      throw new Error(payload.error || \"Could not select level\");\n"
    "    }\n"
    "    const data = await res.json();\n"
    "    applyGameState(data);\n"
    "    setStatus(\"Loaded \" + (data.levelLabel || levelLabel(level)));\n"
    "  } catch (error) {\n"
    "    setStatus(\"Level change failed: \" + error.message, true);\n"
    "    fetchState();\n"
    "  } finally {\n"
    "    selectingLevel = false;\n"
    "  }\n"
    "}\n"
    "async function fetchState() {\n"
    "  try {\n"
    "    const res = await fetch(\"/state\", { cache: \"no-store\" });\n"
    "    if (!res.ok) throw new Error(`State request failed with ${res.status}`);\n"
    "    const data = await res.json();\n"
    "    if (!Array.isArray(data.nodes)) throw new Error(\"Malformed /state payload\");\n"
    "    applyGameState(data);\n"
    "    lastGoodUpdateMs = Date.now();\n"
    "    failStreak = 0;\n"
    "    setStatus(\"Live - \" + new Date(lastGoodUpdateMs).toLocaleTimeString());\n"
    "  } catch (error) {\n"
    "    failStreak += 1;\n"
    "    if (failStreak >= 3) setStatus(`Connection issue: ${error.message}`, true);\n"
    "  }\n"
    "}\n"
    "async function toggleSwitch(name) {\n"
    "  if (inFlightToggles.has(name)) return;\n"
    "  inFlightToggles.add(name);\n"
    "  try {\n"
    "    const res = await fetch(`/toggle?name=${encodeURIComponent(name)}`, { method: \"POST\" });\n"
    "    if (!res.ok) {\n"
    "      const payload = await res.json().catch(() => ({}));\n"
    "      throw new Error(payload.error || `toggle failed (${res.status})`);\n"
    "    }\n"
    "    const data = await res.json();\n"
    "    if (Array.isArray(data.nodes)) {\n"
    "      applyGameState(data);\n"
    "      lastGoodUpdateMs = Date.now();\n"
    "      setStatus(\"Live - \" + new Date(lastGoodUpdateMs).toLocaleTimeString());\n"
    "    }\n"
    "  } catch (error) { setStatus(`Toggle failed: ${error.message}`, true); }\n"
    "  finally { inFlightToggles.delete(name); }\n"
    "}\n"
    "levelSelect.addEventListener(\"change\", function() { selectLevel(levelSelect.value); });\n"
    "setInterval(fetchState, POLL_MS);\n"
    "fetchState();\n";

const size_t LG_APP_JS_LEN = sizeof(LG_APP_JS) - 1;
