#include "embedded_assets.h"

const char LG_INDEX_HTML[] =
    /* Minimal shell for the game UI. */
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "  <meta charset=\"UTF-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "  <title>Logic Gate Game</title>\n"
    "  <link rel=\"stylesheet\" href=\"/styles.css\">\n"
    "</head>\n"
    "<body>\n"
    "  <main class=\"game-shell\">\n"
    "    <header class=\"hud\">\n"
    "      <div class=\"badge\">Moves: <span id=\"moves\">0</span></div>\n"
    "      <div id=\"status\" class=\"badge status\">Connecting...</div>\n"
    "      <div class=\"badge level-control\">Level: <select id=\"levelSelect\"></select></div>\n"
    "      <button type=\"button\" id=\"themeToggle\" class=\"ctrl theme-toggle\">Dark</button>\n"
    "      <div id=\"winBanner\" class=\"badge win-banner\" hidden>Level Complete!</div>\n"
    "    </header>\n"
    "    <section class=\"workspace\">\n"
    "    <section class=\"board\">\n"
    "      <svg class=\"wires\" viewBox=\"0 0 1000 620\" preserveAspectRatio=\"none\">\n"
    "        <polyline id=\"wire-sa-and\" points=\"120,180 300,180 300,320 420,320\" />\n"
    "        <polyline id=\"wire-sb-and\" points=\"120,350 315,350 315,360 420,360\" />\n"
    "        <polyline id=\"wire-sa-not\" points=\"120,180 280,180 280,110 400,110\" />\n"
    "        <polyline id=\"wire-and-or\" points=\"560,340 660,340 660,240 700,240\" />\n"
    "        <polyline id=\"wire-not-or\" points=\"500,110 620,110 620,200 700,200\" />\n"
    "        <polyline id=\"wire-or-bulb\" points=\"840,220 900,220\" />\n"
    "      </svg>\n"

    "      <article class=\"node input\" data-id=\"SwitchA\">\n"
    "        <div class=\"lamp\"></div>\n"
    "        <h3>Switch A</h3>\n"
    "        <p class=\"state\">OFF</p>\n"
    "      </article>\n"

    "      <article class=\"node input\" data-id=\"SwitchB\">\n"
    "        <div class=\"lamp\"></div>\n"
    "        <h3>Switch B</h3>\n"
    "        <p class=\"state\">OFF</p>\n"
    "      </article>\n"

    "      <article class=\"node gate small\" data-id=\"NotA\">\n"
    "        <h3>NOT</h3>\n"
    "        <div class=\"lamp\"></div>\n"
    "      </article>\n"

    "      <article class=\"node gate\" data-id=\"And1\">\n"
    "        <h3>AND</h3>\n"
    "        <div class=\"lamp\"></div>\n"
    "      </article>\n"

    "      <article class=\"node gate\" data-id=\"Or1\">\n"
    "        <h3>OR</h3>\n"
    "        <div class=\"lamp\"></div>\n"
    "      </article>\n"

    "      <article class=\"node output\" data-id=\"Bulb1\">\n"
    "        <div class=\"lamp\"></div>\n"
    "        <h3>Bulb</h3>\n"
    "      </article>\n"

    "    </section>\n"
    "      <aside id=\"signalStack\" class=\"signal-stack\"></aside>\n"
    "    </section>\n"
    "  </main>\n"
    "  <script src=\"/app.js\"></script>\n"
    "</body>\n"
    "</html>\n";

const size_t LG_INDEX_HTML_LEN = sizeof(LG_INDEX_HTML) - 1;

const char LG_STYLES_CSS[] =
    /* Theme tokens and compact layout styles. */
    ":root {\n"
    "  --bg-0: #f4f6f8;\n"
    "  --bg-1: #e8edf2;\n"
    "  --ink-0: #15202b;\n"
    "  --ink-1: #5b6b78;\n"
    "  --line: #d6dee7;\n"
    "  --card: rgba(255,255,255,0.82);\n"
    "  --card-edge: #dfe6ee;\n"
    "  --wire-off: #c0cad4;\n"
    "  --wire-on: #3b7f59;\n"
    "  --lamp-off: #cc604b;\n"
    "  --lamp-on: #3aa76d;\n"
    "  --shell: rgba(255,255,255,0.55);\n"
    "  --panel: rgba(255,255,255,0.66);\n"
    "}\n"
    "body[data-theme=\"dark\"] {\n"
    "  --bg-0: #11161d;\n"
    "  --bg-1: #18212b;\n"
    "  --ink-0: #ecf1f6;\n"
    "  --ink-1: #a8b4bf;\n"
    "  --line: #32404d;\n"
    "  --card: rgba(22,29,38,0.84);\n"
    "  --card-edge: #34414f;\n"
    "  --wire-off: #566575;\n"
    "  --wire-on: #42c17a;\n"
    "  --lamp-off: #d26c57;\n"
    "  --lamp-on: #4fd58a;\n"
    "  --shell: rgba(16,21,28,0.64);\n"
    "  --panel: rgba(20,26,34,0.72);\n"
    "}\n"
    "* { box-sizing: border-box; user-select: none; }\n"
    "body {\n"
    "  margin: 0; min-height: 100vh; display: grid; place-items: center;\n"
    "  font-family: \"Segoe UI\", \"Helvetica Neue\", Arial, sans-serif;\n"
    "  background: radial-gradient(circle at 20% 0%, rgba(255,255,255,0.92) 0%, var(--bg-0) 38%, var(--bg-1) 100%);\n"
    "  color: var(--ink-0); overflow: hidden; transition: background 180ms ease, color 180ms ease;\n"
    "}\n"
    ".game-shell { width: min(1220px, 98vw); padding: 14px 16px 16px; }\n"
    ".hud { display: flex; justify-content: space-between; align-items: center; gap: 12px; margin-bottom: 12px; flex-wrap: wrap; }\n"
    ".badge {\n"
    "  background: var(--panel);\n"
    "  border: 1px solid var(--line); border-radius: 999px;\n"
    "  padding: 8px 14px; font-weight: 600; letter-spacing: 0.01em;\n"
    "  color: var(--ink-0); box-shadow: 0 6px 18px rgba(22,43,66,0.06);\n"
    "}\n"
    ".status { min-width: 260px; text-align: center; font-weight: 700; }\n"
    ".level-control { min-width: 180px; }\n"
    ".level-control select {\n"
    "  margin-left: 6px; border: 1px solid var(--line); border-radius: 8px;\n"
    "  background: var(--card); color: var(--ink-0); padding: 4px 8px;\n"
    "}\n"
    ".workspace { display: grid; grid-template-columns: minmax(0, 1fr) 150px; gap: 14px; align-items: start; }\n"
    ".board {\n"
    "  position: relative; width: 100%; height: min(74vh, 650px);\n"
    "  border-radius: 20px; border: 1px solid var(--line);\n"
    "  background:\n"
    "    linear-gradient(transparent 31px, rgba(142,164,185,0.13) 32px),\n"
    "    linear-gradient(90deg, transparent 31px, rgba(142,164,185,0.13) 32px),\n"
    "    linear-gradient(180deg, var(--bg-0), var(--bg-1));\n"
    "  background-size: 32px 32px, 32px 32px, 100% 100%;\n"
    "  box-shadow: 0 14px 32px rgba(17,42,68,0.10);\n"
    "}\n"
    ".wires { position: absolute; inset: 0; width: 100%; height: 100%; }\n"
    ".wires polyline {\n"
    "  fill: none; stroke: var(--wire-off); stroke-width: 5;\n"
    "  stroke-linecap: round; stroke-linejoin: round;\n"
    "  transition: stroke 140ms ease, opacity 140ms ease; opacity: 0.9;\n"
    "}\n"
    ".wires polyline.on { stroke: var(--wire-on); opacity: 1; }\n"
    ".node {\n"
    "  position: absolute; background: var(--card); backdrop-filter: blur(8px);\n"
    "  border: 1px solid var(--card-edge); border-radius: 12px;\n"
    "  box-shadow: 0 8px 20px rgba(16,39,61,0.08);\n"
    "  display: grid; place-items: center; gap: 6px;\n"
    "  color: var(--ink-0);\n"
    "  touch-action: none;\n"
    "  transition: transform 130ms ease, box-shadow 130ms ease, border-color 130ms ease, background 180ms ease;\n"
    "}\n"
    ".node h3 { margin: 0; font-size: clamp(0.95rem, 1.7vw, 1.35rem); font-weight: 600; letter-spacing: 0.02em; }\n"
    ".node .state { margin: 0; font-size: 0.75rem; letter-spacing: 0.08em; font-weight: 700; color: var(--ink-1); }\n"
    ".node.input { width: 120px; height: 150px; left: 3%; }\n"
    ".node.input[data-id=\"SwitchA\"] { top: 12%; }\n"
    ".node.input[data-id=\"SwitchB\"] { top: 44%; }\n"
    ".node.gate { width: 132px; height: 116px; }\n"
    ".node.gate.small { width: 110px; height: 88px; }\n"
    ".node.gate[data-id=\"NotA\"] { left: 40%; top: 8%; }\n"
    ".node.gate[data-id=\"And1\"] { left: 42%; top: 45%; }\n"
    ".node.gate[data-id=\"Or1\"] { left: 64%; top: 25%; }\n"
    ".node.output { width: 112px; height: 120px; }\n"
    ".node.output h3 { font-size: 1.05rem; }\n"
    ".node.toggleable { cursor: pointer; }\n"
    ".node.dragging { cursor: grabbing; transform: scale(1.01); z-index: 4; }\n"
    ".node.draggable { cursor: grab; }\n"
    ".node.toggleable:hover { transform: translateY(-2px); border-color: #a9bfd6; }\n"
    ".node.active { border-color: #95cfa4; box-shadow: 0 12px 30px rgba(34,117,61,0.18); }\n"
    ".lamp {\n"
    "  width: 20px; height: 20px; border-radius: 50%;\n"
    "  border: 1px solid #aeb9c6; background: var(--lamp-off);\n"
    "  box-shadow: 0 0 0 4px rgba(216,97,79,0.13);\n"
    "}\n"
    ".lamp.on {\n"
    "  background: var(--lamp-on);\n"
    "  box-shadow: 0 0 0 4px rgba(69,196,103,0.18), 0 0 18px rgba(69,196,103,0.45);\n"
    "}\n"
    ".signal-stack {\n"
    "  position: sticky; top: 14px; width: 100%;\n"
    "  display: grid; gap: 8px; padding: 14px 10px;\n"
    "  border: 1px solid var(--line); border-radius: 18px;\n"
    "  background: var(--panel); backdrop-filter: blur(8px);\n"
    "  box-shadow: 0 10px 24px rgba(17,42,68,0.06);\n"
    "}\n"
    ".signal-row {\n"
    "  display: flex; align-items: center; justify-content: space-between;\n"
    "  background: var(--card); border: 1px solid var(--line);\n"
    "  border-radius: 8px; padding: 6px 8px; font-size: 0.72rem; font-weight: 600; color: var(--ink-1);\n"
    "}\n"
    ".signal-dot {\n"
    "  width: 12px; height: 12px; border-radius: 50%; border: 1px solid #aeb9c6;\n"
    "  background: var(--lamp-off);\n"
    "}\n"
    ".signal-dot.on { background: var(--lamp-on); box-shadow: 0 0 10px rgba(69,196,103,0.45); }\n"
    ".win-banner { background: rgba(58,167,109,0.10); border-color: rgba(58,167,109,0.28); color: var(--ink-0); font-weight: 700; }\n"
    ".theme-toggle { min-width: 84px; }\n"
    ".ctrl {\n"
    "  border: 1px solid var(--line); background: var(--card);\n"
    "  color: var(--ink-1); font-weight: 600; letter-spacing: 0.02em;\n"
    "  border-radius: 10px; min-width: 76px; padding: 10px 12px;\n"
    "  box-shadow: 0 6px 20px rgba(20,42,64,0.08);\n"
    "}\n"
    ".ctrl:hover { border-color: #b4c7db; color: var(--ink-0); }\n"
    "@media (max-width: 900px) {\n"
    "  .workspace { grid-template-columns: 1fr; }\n"
    "  .board { height: 78vh; }\n"
    "  .signal-stack { position: static; width: 100%; grid-template-columns: repeat(3, minmax(0, 1fr)); padding: 8px; }\n"
    "  .status { min-width: 0; flex: 1 1 100%; }\n"
    "}\n";

const size_t LG_STYLES_CSS_LEN = sizeof(LG_STYLES_CSS) - 1;

const char LG_APP_JS[] =
    /* Poll the backend and keep the board in sync. */
    "const POLL_MS = 150;\n"
    "const statusNode = document.getElementById(\"status\");\n"
    "const movesNode = document.getElementById(\"moves\");\n"
    "const levelSelect = document.getElementById(\"levelSelect\");\n"
    "const themeToggle = document.getElementById(\"themeToggle\");\n"
    "const winBanner = document.getElementById(\"winBanner\");\n"
    "const signalStack = document.getElementById(\"signalStack\");\n"
    "const board = document.querySelector(\".board\");\n"
    "const wiresSvg = document.querySelector(\".wires\");\n"
    "const inFlightToggles = new Set();\n"
    "const signalState = new Map();\n"
    "let edgeDefs = [];\n"
    "let levelCatalog = [];\n"
    "let latestState = null;\n"
    "let moves = 0;\n"
    "let moveLimit = 0;\n"
    "let failStreak = 0;\n"
    "let selectingLevel = false;\n"
    "let currentTheme = \"light\";\n"

    "// Keep the chosen theme stable across reloads.\n"
    "function applyTheme(theme) {\n"
    "  currentTheme = theme === \"dark\" ? \"dark\" : \"light\";\n"
    "  document.body.dataset.theme = currentTheme;\n"
    "  if (themeToggle) themeToggle.textContent = currentTheme === \"dark\" ? \"Light\" : \"Dark\";\n"
    "  try { localStorage.setItem(\"logic-gate-theme\", currentTheme); } catch (error) {}\n"
    "}\n"
    "function initTheme() {\n"
    "  let stored = null;\n"
    "  try { stored = localStorage.getItem(\"logic-gate-theme\"); } catch (error) {}\n"
    "  applyTheme(stored || (window.matchMedia && window.matchMedia(\"(prefers-color-scheme: dark)\").matches ? \"dark\" : \"light\"));\n"
    "}\n"

    "function escId(id) {\n"
    "  return typeof CSS !== \"undefined\" && CSS.escape ? CSS.escape(id) : id.replace(/[^a-zA-Z0-9_-]/g, \"\");\n"
    "}\n"
    "function clamp(value, min, max) {\n"
    "  return Math.max(min, Math.min(max, value));\n"
    "}\n"
    "function setStatus(text, isError = false) {\n"
    "  statusNode.textContent = text;\n"
    "  statusNode.style.color = isError ? \"#c34f3f\" : \"var(--ink-0)\";\n"
    "}\n"
    "function levelLabel(key) {\n"
    "  const level = levelCatalog.find(function(item) { return item.id === key; });\n"
    "  return level && level.label ? level.label : key;\n"
    "}\n"
    "function levelOrderValue(key) {\n"
    "  const match = /^level(\\d+)$/.exec(String(key || \"\").toLowerCase());\n"
    "  if (!match) return 1000;\n"
    "  return parseInt(match[1], 10);\n"
    "}\n"
    "function boardRect() {\n"
    "  return board.getBoundingClientRect();\n"
    "}\n"
    "function nodeElement(id) {\n"
    "  return document.querySelector(\".node[data-id=\\\"\" + escId(id) + \"\\\"]\");\n"
    "}\n"
    "function gateLabel(node) {\n"
    "  if (node.type === \"InputSwitch\") return node.id === \"SwitchA\" ? \"Switch A\" : \"Switch B\";\n"
    "  if (node.type === \"Bulb\") return \"Bulb\";\n"
    "  return String(node.type || \"Gate\").toUpperCase();\n"
    "}\n"
    "function ensureNode(node) {\n"
    "  let el = nodeElement(node.id);\n"
    "  if (!el) {\n"
    "    el = document.createElement(\"article\");\n"
    "    el.className = \"node\";\n"
    "    el.dataset.id = node.id;\n"
    "    el.innerHTML = \"<div class=\\\"lamp\\\"></div><h3></h3><p class=\\\"state\\\">OFF</p>\";\n"
    "    board.appendChild(el);\n"
    "  }\n"
    "  el.classList.remove(\"input\", \"gate\", \"output\", \"small\");\n"
    "  if (node.type === \"InputSwitch\") {\n"
    "    el.classList.add(\"input\");\n"
    "  } else if (node.type === \"Bulb\") {\n"
    "    el.classList.add(\"output\");\n"
    "  } else {\n"
    "    el.classList.add(\"gate\");\n"
    "  }\n"
    "  if (node.type === \"Not\") el.classList.add(\"small\");\n"
    "  const title = el.querySelector(\"h3\");\n"
    "  if (title) title.textContent = gateLabel(node);\n"
    "  return el;\n"
    "}\n"
    "function setNodePosition(el, x, y) {\n"
    "  const rect = boardRect();\n"
    "  if (!el || rect.width <= 0 || rect.height <= 0) return;\n"
    "  const maxX = Math.max(0, 1 - (el.offsetWidth / rect.width));\n"
    "  const maxY = Math.max(0, 1 - (el.offsetHeight / rect.height));\n"
    "  const clampedX = clamp(Number(x) || 0, 0, maxX);\n"
    "  const clampedY = clamp(Number(y) || 0, 0, maxY);\n"
    "  el.style.left = String(clampedX * 100) + \"%\";\n"
    "  el.style.top = String(clampedY * 100) + \"%\";\n"
    "}\n"
    "function anchorPoint(el, side) {\n"
    "  const b = boardRect();\n"
    "  const r = el.getBoundingClientRect();\n"
    "  const left = r.left - b.left;\n"
    "  const top = r.top - b.top;\n"
    "  if (side === \"left\") return { x: left, y: top + r.height * 0.5 };\n"
    "  return { x: left + r.width, y: top + r.height * 0.5 };\n"
    "}\n"
    "function wirePoints(start, end) {\n"
    "  const bendX = start.x + Math.max(24, (end.x - start.x) * 0.5);\n"
    "  return [\n"
    "    Math.round(start.x), Math.round(start.y),\n"
    "    Math.round(bendX), Math.round(start.y),\n"
    "    Math.round(bendX), Math.round(end.y),\n"
    "    Math.round(end.x), Math.round(end.y)\n"
    "  ].join(\",\");\n"
    "}\n"
    "function syncEdges(edges) {\n"
    "  edgeDefs = Array.isArray(edges) ? edges.slice() : [];\n"
    "  wiresSvg.innerHTML = \"\";\n"
    "  edgeDefs.forEach(function(edge, idx) {\n"
    "    const line = document.createElementNS(\"http://www.w3.org/2000/svg\", \"polyline\");\n"
    "    line.id = \"edge-\" + idx;\n"
    "    line.dataset.from = edge.from;\n"
    "    line.dataset.to = edge.to;\n"
    "    wiresSvg.appendChild(line);\n"
    "  });\n"
    "}\n"
    "function updateWireGeometry() {\n"
    "  const lines = wiresSvg.querySelectorAll(\"polyline\");\n"
    "  lines.forEach(function(line) {\n"
    "    const from = nodeElement(line.dataset.from);\n"
    "    const to = nodeElement(line.dataset.to);\n"
    "    if (!from || !to) return;\n"
    "    const start = anchorPoint(from, \"right\");\n"
    "    const end = anchorPoint(to, \"left\");\n"
    "    line.setAttribute(\"points\", wirePoints(start, end));\n"
    "    line.classList.toggle(\"on\", !!signalState.get(line.dataset.from));\n"
    "  });\n"
    "}\n"
    "function updateSignalStack(nodes) {\n"
    "  signalStack.innerHTML = nodes.map(function(node) {\n"
    "    return \"<div class=\\\"signal-row\\\"><span>\" + node.id + \"</span><span class=\\\"signal-dot \" + (node.state ? \"on\" : \"\") + \"\\\"></span></div>\";\n"
    "  }).join(\"\");\n"
    "}\n"
    "async function toggleSwitch(name) {\n"
    "  if (inFlightToggles.has(name)) return;\n"
    "  inFlightToggles.add(name);\n"
    "  try {\n"
    "    const res = await fetch(\"/toggle?name=\" + encodeURIComponent(name), { method: \"POST\" });\n"
    "    if (!res.ok) {\n"
    "      const payload = await res.json().catch(function() { return {}; });\n"
    "      throw new Error(payload.error || \"toggle failed\");\n"
    "    }\n"
    "    const data = await res.json();\n"
    "    applyGameState(data);\n"
    "  } catch (error) {\n"
    "    setStatus(\"Toggle failed: \" + error.message, true);\n"
    "  } finally {\n"
    "    inFlightToggles.delete(name);\n"
    "  }\n"
    "}\n"
    "function reconcileNodes(nodes) {\n"
    "  const keep = new Set();\n"
    "  signalState.clear();\n"
    "  nodes.forEach(function(node) {\n"
    "    const el = ensureNode(node);\n"
    "    keep.add(node.id);\n"
    "    signalState.set(node.id, !!node.state);\n"
    "    el.classList.toggle(\"active\", !!node.state);\n"
    "    el.classList.toggle(\"toggleable\", !!node.toggleable);\n"
    "    el.onclick = node.toggleable ? function() { toggleSwitch(node.id); } : null;\n"
    "    const lamp = el.querySelector(\".lamp\");\n"
    "    const state = el.querySelector(\".state\");\n"
    "    if (lamp) lamp.classList.toggle(\"on\", !!node.state);\n"
    "    if (state) state.textContent = node.state ? \"ON\" : \"OFF\";\n"
    "    setNodePosition(el, node.x, node.y);\n"
    "  });\n"
    "  document.querySelectorAll(\".node\").forEach(function(el) {\n"
    "    if (!keep.has(el.dataset.id)) el.remove();\n"
    "  });\n"
    "}\n"
    "function renderLevelOptions(data) {\n"
    "  const unlocked = data.unlocked || {};\n"
    "  const levels = levelCatalog.length ? levelCatalog.slice() : Object.keys(unlocked).sort(function(a, b) { return levelOrderValue(a) - levelOrderValue(b); }).map(function(key) {\n"
    "    return { id: key, label: key };\n"
    "  });\n"
    "  levelSelect.innerHTML = levels.map(function(level) {\n"
    "    const isUnlocked = !!unlocked[level.id] || level.id === data.level;\n"
    "    const lock = isUnlocked ? \"\" : \" (Locked)\";\n"
    "    return \"<option value=\\\"\" + level.id + \"\\\" \" + (isUnlocked ? \"\" : \"disabled\") + \">\" + (level.label || level.id) + lock + \"</option>\";\n"
    "  }).join(\"\");\n"
    "  if (data.level) levelSelect.value = data.level;\n"
    "}\n"

    "function renderWin(data) {\n"
    "  if (data.won) {\n"
    "    winBanner.hidden = false;\n"
    "    winBanner.textContent = \"Level Complete: \" + (data.levelLabel || levelLabel(data.level));\n"
    "  } else {\n"
    "    winBanner.hidden = true;\n"
    "  }\n"
    "}\n"
    "function applyGameState(data) {\n"
    "  if (!Array.isArray(data.nodes)) return;\n"
    "  latestState = data;\n"
    "  moves = typeof data.moves === \"number\" ? data.moves : moves;\n"
    "  moveLimit = typeof data.moveLimit === \"number\" ? data.moveLimit : moveLimit;\n"
    "  movesNode.textContent = moveLimit > 0 ? String(moves) + \"/\" + String(moveLimit) : String(moves);\n"
    "  reconcileNodes(data.nodes);\n"
    "  syncEdges(data.edges || []);\n"
    "  updateWireGeometry();\n"
    "  updateSignalStack(data.nodes);\n"
    "  renderLevelOptions(data);\n"
    "  renderWin(data);\n"
    "}\n"
    "async function fetchLevels() {\n"
    "  try {\n"
    "    const res = await fetch(\"/levels\", { cache: \"no-store\" });\n"
    "    if (!res.ok) throw new Error(\"Failed to load levels\");\n"
    "    const data = await res.json();\n"
    "    levelCatalog = Array.isArray(data.levels) ? data.levels.slice().sort(function(a, b) {\n"
    "      return levelOrderValue(a.id) - levelOrderValue(b.id);\n"
    "    }) : [];\n"
    "    if (latestState) renderLevelOptions(latestState);\n"
    "  } catch (error) {\n"
    "    levelCatalog = [];\n"
    "  }\n"
    "}\n"
    "async function selectLevel(level) {\n"
    "  if (!level || selectingLevel) return;\n"
    "  selectingLevel = true;\n"
    "  try {\n"
    "    const res = await fetch(\"/select-level?level=\" + encodeURIComponent(level), { method: \"POST\" });\n"
    "    if (!res.ok) {\n"
    "      const payload = await res.json().catch(function() { return {}; });\n"
    "      throw new Error(payload.error || \"Could not select level\");\n"
    "    }\n"
    "    applyGameState(await res.json());\n"
    "    fetchLevels();\n"
    "    setStatus(\"Loaded \" + levelLabel(level));\n"
    "  } catch (error) {\n"
    "    setStatus(\"Level change failed: \" + error.message, true);\n"
    "    fetchState();\n"
    "  } finally {\n"
    "    selectingLevel = false;\n"
    "  }\n"
    "}\n"
    "async function fetchState() {\n"
    "  try {\n"
    "    const res = await fetch(\"/state\", { cache: \"no-store\" });\n"
    "    if (!res.ok) throw new Error(\"State request failed with \" + res.status);\n"
    "    const data = await res.json();\n"
    "    applyGameState(data);\n"
    "    failStreak = 0;\n"
    "    if (statusNode.textContent === \"Connecting...\" || statusNode.textContent.indexOf(\"Connection issue\") === 0) {\n"
    "      setStatus(\"Connected\");\n"
    "    }\n"
    "  } catch (error) {\n"
    "    failStreak += 1;\n"
    "    if (failStreak >= 3) setStatus(\"Connection issue: \" + error.message, true);\n"
    "  }\n"
    "}\n"
    "if (themeToggle) themeToggle.addEventListener(\"click\", function() { applyTheme(currentTheme === \"dark\" ? \"light\" : \"dark\"); });\n"
    "levelSelect.addEventListener(\"change\", function() { selectLevel(levelSelect.value); });\n"
    "window.addEventListener(\"resize\", updateWireGeometry);\n"
    "initTheme();\n"
    "fetchLevels();\n"
    "setInterval(fetchState, POLL_MS);\n"
    "fetchState();\n";

const size_t LG_APP_JS_LEN = sizeof(LG_APP_JS) - 1;
